import nodemailer from "nodemailer";

export const getTransporter = () => {
  return nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 587,
    secure: false,
    auth: {
      user: process.env.SMTP_EMAIL,
      pass: process.env.SMTP_PASSWORD,
    },
  });
};

/**
 * emailWrapper - Uses --color-gray-50 (#FAF6F0) for background
 * and --color-gray-100 (#EBE5D9) for borders.
 */
const emailWrapper = (content, footerNote) => `
  <div style="background-color: #FAF6F0; padding: 40px 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
    <div style="max-width: 650px; margin: 0 auto; background-color: #ffffff; border: 1px solid #EBE5D9; border-radius: 24px; padding: 40px; color: #1C1814; line-height: 1.6; font-size: 15px; shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
      
      <div style="padding-bottom: 30px;">
        ${content}
      </div>
      
      <hr style="border: none; border-top: 1px solid #EBE5D9; margin: 0 0 20px 0;" />
      
      <div style="font-size: 12px; color: #857666; line-height: 1.5;">
        <p style="margin: 0 0 8px 0;">${footerNote}</p>
        <p style="margin: 0;">&copy; ${new Date().getFullYear()} Bambu. All rights reserved.</p>
      </div>
    </div>
  </div>
`;

/**
 * getDefaultSignature - Uses --color-brand-900 (#184C16) 
 * and --color-brown-500 (#B18F6C)
 */
const getDefaultSignature = () => {

  return `
    <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #EBE5D9;">
      <table style="border-collapse: collapse; margin: 0;">
        <tr>
          <td style="padding-right: 20px; border-right: 2px solid #184C16; vertical-align: middle;">
            <img src="https://res.cloudinary.com/dkh0hsbjg/image/upload/v1773570075/logo-beige_taidas.png" alt="Bambu Logo" style="width: 50px; height: auto; display: block; margin-bottom: 8px;" />
            <strong style="color: #184C16; font-size: 18px; letter-spacing: 2px; margin: 0; display: block; text-transform: uppercase;">BAMBU</strong>
          </td>
          <td style="padding-left: 20px; font-size: 13px; color: #4D433A; line-height: 1.6; vertical-align: middle;">
            <a href="https://bambu-services.com" style="color: #184C16; text-decoration: none; font-weight: 700;">bambu-services.com</a><br/>
            <a href="mailto:contact@bambu-services.com" style="color: #4D433A; text-decoration: none;">contact@bambu-services.com</a><br/>
            <span style="color: #857666; font-weight: 500;">+33 6 41 08 90 49</span>
          </td>
        </tr>
      </table>
    </div>
  `; 
};

export const getContactTemplates = (data) => {
  const { firstName, lastName, subject, message, language, email, phone, wantsPhoneMeeting } = data;
  const isFr = language === "fr";

  const doNotReplyNote = isFr
    ? "Ceci est un e-mail automatique généré par le système Bambu."
    : "This is an automated email generated by the Bambu system.";

  const adminFooterNote = "Bambu internal notification. Please process this request in your CRM.";

  return {
    // --- USER TEMPLATE ---
    user: {
      subject: isFr
        ? "Bambu - Nous avons bien reçu votre message"
        : "Bambu - We have received your message",
      html: emailWrapper(
        `
        <p style="margin-top: 0; font-size: 18px; font-weight: 700; color: #184C16;">
          ${isFr ? `Bonjour ${firstName},` : `Hello ${firstName},`}
        </p>
        
        <p style="color: #4D433A; font-size: 16px;">
          ${isFr 
            ? "Merci de nous avoir contactés. Nous avons bien reçu votre demande concernant votre projet." 
            : "Thank you for reaching out. We have successfully received your inquiry regarding your project."}
        </p>
        
        <p style="color: #4D433A;">
          ${isFr 
            ? "Notre équipe étudie actuellement votre message et reviendra vers vous très prochainement." 
            : "Our team is currently reviewing your message and will get back to you shortly."}
        </p>
        
        ${getDefaultSignature()}
      `,
        doNotReplyNote,
      ),
    },

    // --- ADMIN TEMPLATE ---
    admin: {
      subject: `[New Lead] ${subject} - ${firstName} ${lastName}`,
      html: emailWrapper(
        `
        <div style="margin-bottom: 30px;">
          <span style="background-color: #e3efe1; color: #184C16; padding: 6px 12px; border-radius: 12px; font-size: 12px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px;">
            New Contact Request
          </span>
          <h2 style="margin-top: 15px; color: #1C1814; font-size: 24px; font-weight: 800;">${firstName} ${lastName}</h2>
        </div>
        
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px; font-size: 14px;">
          <tr>
            <td style="padding: 12px 0; border-bottom: 1px solid #EBE5D9; color: #857666; font-weight: 600; width: 150px;">Subject</td>
            <td style="padding: 12px 0; border-bottom: 1px solid #EBE5D9; color: #1C1814; font-weight: 700;">${subject}</td>
          </tr>
          <tr>
            <td style="padding: 12px 0; border-bottom: 1px solid #EBE5D9; color: #857666; font-weight: 600;">Email</td>
            <td style="padding: 12px 0; border-bottom: 1px solid #EBE5D9; color: #184C16; font-weight: 700;">
              <a href="mailto:${email}" style="color: #184C16; text-decoration: none;">${email}</a>
            </td>
          </tr>
          <tr>
            <td style="padding: 12px 0; border-bottom: 1px solid #EBE5D9; color: #857666; font-weight: 600;">Phone</td>
            <td style="padding: 12px 0; border-bottom: 1px solid #EBE5D9; color: #1C1814;">${phone || '<span style="color: #D6CDC0;">Not provided</span>'}</td>
          </tr>
          <tr>
            <td style="padding: 12px 0; border-bottom: 1px solid #EBE5D9; color: #857666; font-weight: 600;">Callback Requested</td>
            <td style="padding: 12px 0; border-bottom: 1px solid #EBE5D9; color: ${wantsPhoneMeeting ? "#447331" : "#A19382"}; font-weight: 800;">
              ${wantsPhoneMeeting ? "YES ✅" : "NO"}
            </td>
          </tr>
          <tr>
            <td style="padding: 12px 0; border-bottom: 1px solid #EBE5D9; color: #857666; font-weight: 600;">Language</td>
            <td style="padding: 12px 0; border-bottom: 1px solid #EBE5D9; color: #1C1814; text-transform: uppercase;">${language}</td>
          </tr>
        </table>
        
        <p style="margin: 0 0 10px 0; color: #B18F6C; font-size: 12px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px;">User Message</p>
        <div style="background-color: #f2f8f1; border: 1px solid #c9dec6; border-radius: 16px; padding: 25px; color: #1C1814; white-space: pre-wrap; font-size: 15px; line-height: 1.7;">${message}</div>
      `,
        adminFooterNote,
      ),
    },
  };
};